---
title: "Hems Blog"
date: 2022-05-09
---
theme: minima
title: Hemory's Blid
author: Hemory Phifer
email: hemory@github.com
description: > # this means to ignore newlines until "baseurl:"
  Peep game!
# social links
twitter_username: heminthehat
github_username:  hemory

show_excerpts: true # set to false to remove excerpts on the homepage
